services:
    app:
        image: aegislabs-laravel
        container_name: aegislabs-app
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        depends_on:
            - redis
            - postgresql
        ports:
            - "8080:80"
        volumes:
            - ..:/app
        environment:
            CONTAINER_ROLE: app
            APP_ENV: local
            CACHE_DRIVER: redis
            SESSION_DRIVER: redis
            QUEUE_DRIVER: redis
            REDIS_HOST: redis
            MAIL_MAILER: smtp
            MAIL_HOST: mailpit
            PHP_IDE_CONFIG: "serverName=localhost"
    queue:
        image: aegislabs-laravel
        container_name: aegislabs-queue
        depends_on:
            - app
        volumes:
            - ..:/app
        environment:
            CONTAINER_ROLE: queue
            APP_ENV: local
            CACHE_DRIVER: redis
            SESSION_DRIVER: redis
            QUEUE_DRIVER: redis
            REDIS_HOST: redis
            PHP_IDE_CONFIG: "serverName=localhost"
    redis:
        image: redis:7.4.1-alpine
        container_name: aegislabs-redis
        ports:
            - "16379:6379"
        volumes:
            - redis:/data
    postgresql:
        container_name: aegislabs-postgresql
        image: postgres:17.2-alpine
        ports:
            - "15432:5432"
        volumes:
            - postgresql:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: aegislabs
            POSTGRES_USER: aegisadmin
            POSTGRES_PASSWORD: password12345
    mailpit:
        image: axllent/mailpit
        container_name: aegislabs-mailpit
        profiles:
            - dev
        ports:
            - "18025:8025"
            - "11025:1025"
        volumes:
            - mailpit:/data
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
volumes:
    redis:
        driver: "local"
    postgresql:
        driver: "local"
    mailpit:
        driver: "local"
